sequenceDiagram
    Alice->>John: Hello John, how are you?
    activate John
    John-->>Alice: Great!
    deactivate John
    Alice->>John: John, can you hear me?
    activate John
    John-->>Alice: Hi Alice!
    deactivate John
