gitGraph
  commit id: "A" tag: "v1.0.0"
  commit id: "B" type: REVERSE
  commit id: "C" type: HIGHLIGHT
  branch feature
  checkout feature
  commit id: "D"
  checkout main
  merge feature id: "E" tag: "v1.1.0"
