flowchart LR
    a("`The **cat**
    in the hat`") -- "edge label" --> b{{"`The **dog** in the hog`"}}
    b --> c["A label with #quot;quotes#quot; and a heart #9829;"]
    c --> d["Line one<br/>Line two<br>Line three"]
