flowchart LR
    A[Rectangle]
    B(Rounded)
    C([Stadium])
    D[[Subroutine]]
    E[(Cylinder)]
    F((Circle))
    G{Diamond}
    H{{Hexagon}}
    I>Asymmetric]
    J[/Parallelogram\]
    K[\Parallelogram/]
    L@{ shape: doc, label: "Document" }
    M@{ shape: cyl, label: "Database" }
    N@{ shape: dbl-circ, label: "Double" }
    
    A --> B --> C --> D --> E --> F --> G --> H --> I --> J --> K --> L --> M --> N
