---
config:
  xyChart:
    showDataLabel: true
---
xychart-beta horizontal
    title "Language popularity"
    x-axis [Go, Rust, Python, TypeScript, "C++"]
    y-axis "Score" 0 --> 100
    bar [72, 65, 90, 85, 55]
